#!/bin/bash

# Here only as an example of how to create a release.
# Assuming that /workspace is persisted between
# jobs, else this fails, lol.

export VERSION=$(grep VERSION sorry.nikhil.io/index.html | awk '{print $2}')
export RELEASE_ARTIFACT="sorry.nikhil.io.v$VERSION.tgz"

tar -czvf "$RELEASE_ARTIFACT" sorry.nikhil.io/

ghr \
    -t ${GITHUB_TOKEN} \
    -u ${CIRCLE_PROJECT_USERNAME} \
    -r ${CIRCLE_PROJECT_REPONAME} \
    -c ${CIRCLE_SHA1} \
    -delete ${VERSION} \
    "$RELEASE_ARTIFACT"
