#!/bin/bash

# Here only as an example of how to create a release.
# Assuming that /workspace is persisted between
# jobs, else this fails, lol.

VERSION=$(cat $HOME/project/README.md)
TARBALL="sorry.nikhil.io.v$VERSION.tgz"
tar -czvf "$TARBALL" sorry.nikhil.io/

ghr \
    -t ${GITHUB_TOKEN} \
    -u ${CIRCLE_PROJECT_USERNAME} \
    -r ${CIRCLE_PROJECT_REPONAME} \
    -c ${CIRCLE_SHA1} \
    -delete ${VERSION} \
    "$TARBALL"
